name: Maven Build Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Repository Access
      run: |
        echo "Checking repository root access..."
        curl -I https://clasweb.jlab.org/clas12maven/
        echo "Checking artifact access..."
        curl -I https://clasweb.jlab.org/clas12maven/org/jlab/groot/4.0.5/

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
                  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
                  xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">
          <profiles>
            <profile>
              <id>custom-repo</id>
              <repositories>
                <repository>
                  <id>clas12maven</id>
                  <url>https://clasweb.jlab.org/clas12maven/</url>
                  <snapshots>
                    <enabled>true</enabled>
                  </snapshots>
                </repository>
              </repositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>custom-repo</activeProfile>
          </activeProfiles>
        </settings>" > ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn clean install -U -DskipTests
